openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
components:
  schemas:
    my:
      description: 用户信息
      properties:
        content:
          properties:
            catname:
              type: string
              description: fff

servers:
  - url: https://api.server.test/v1
    description: "开发"
  - url: https://api.server.test/v2
    description: "测试环境"
paths:
  /test:
    get:
      parameters:
        - name: "id"
          in: "path"
          required: true
          description: "用户id"
          schema:
            type: "number"
            format: "int32"

      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    maxLength: 3
                    description: "用户id"
                  name:
                    type: object
                    description: 嵌套结构
                    properties:
                      in:
                        $ref: '#/components/schemas/my'


